apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: httpd-storage
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: httpd-storage
        persistentVolumeClaim:
          claimName: httpd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
