apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-content
data:
  index.html: |
    <html>
      <head>
        <title>Welcome</title>
      </head>
      <body>
        <h1>Welcome to the HTTPD Server!</h1>
      </body>
    </html>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
spec:
  storageClassName: standard  # Changed to 'standard'
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: httpd-storage
          mountPath: /usr/local/apache2/htdocs
        - name: httpd-config
          mountPath: /usr/local/apache2/htdocs/index.html
          subPath: index.html
      volumes:
      - name: httpd-storage
        persistentVolumeClaim:
          claimName: httpd-pvc
      - name: httpd-config
        configMap:
          name: httpd-content
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
